// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaddcourseistructorrelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaddcourseistructorrelations));
        
        string IMigrationMetadata.Id
        {
            get { return "202309141847054_mig-add-course-istructor-relations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
